apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wordsmith-{{ .Values.namespace }}
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - list:
            elements:
            {{ if .Values.api.enabled }}
            - app: wordsmith-api
            {{ end }}
            {{ if .Values.web.enabled }}
            - app: wordsmith-web
            {{ end }}
            {{ if .Values.db.enabled }}
            - app: wordsmith-db
            {{ end }}
        - list:
            elements:
            - namespace: {{ .Values.namespace }}
  template:
    metadata:
      name: '{{"{{"}}namespace{{"}}"}}-{{"{{"}}app{{"}}"}}'
      labels:
        app: '{{"{{"}}namespace{{"}}"}}'
      finalizers: 
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "default"
      source:
        repoURL: git@gitlab.com:sandbox-aziz/{{"{{"}}app{{"}}"}}.git
        targetRevision: HEAD
        path: '.'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{"{{"}}namespace{{"}}"}}'
      syncPolicy:
        automated: 
          prune: true 
          selfHeal: true 
          allowEmpty: false 
        syncOptions:     
        - Validate=false 
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground 
        - PruneLast=true 
        retry:
          limit: -1
          backoff:
            duration: 5s 
            factor: 2
            maxDuration: 3m 
        revisionHistoryLimit: 10